project:
  type: website

website:
  title: "first-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:sources
      
  sidebar:
    - id: sources
      title: "Sources"
      style: "floating"
      background: "#ffffff"
      collapse-level: 2
      contents:
        - source1.qmd
        - source2.qmd
    - id: interactive
      title: "Interactive Pages"
      style: "floating"
      background: "#ffffff"
      collapse-level: 3
      contents: 
        - plane-passengers.qmd
        - map-london.qmd
        - plotly.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



